(function () {
  var STORE_KEY = "alquimia-lang";

  var dict = {
    "Privacy Policy · Alquimia Lab": "Política de Privacidad · Alquimia Lab",
    "Privacy": "Privacidad",
    "Last updated: September 21, 2026": "Última actualización: 21 de Septiembre de 2026",
    "1. General Information": "1. Información General",
    "This Privacy Policy governs the collection, use and protection of your personal information when you visit and use the services of": "Esta Política de Privacidad rige la recopilación, el uso y la protección de tu información personal cuando visitas y utilizas los servicios de",
    "(hereinafter \"us\", \"our\" or \"Alquimia Lab\"), including our website": "(en adelante \"nosotros\", \"nuestro\" o \"Alquimia Lab\"), incluyendo nuestro sitio web",
    ", the mobile application": ", la aplicación móvil",
    "(hereinafter the \"App\" or \"Kore App\") and all associated products, services and content.": "(en adelante \"la App\" o \"Kore App\") y todos los productos, servicios y contenidos asociados.",
    "By accessing or using our services, you accept the practices described in this policy. If you are under 16 years old, you must obtain the consent of a parent or legal guardian before providing any personal information.": "Al acceder o utilizar nuestros servicios, aceptas las prácticas descritas en esta política. Si tienes menos de 16 años, debes obtener el consentimiento de un padre o tutor legal antes de proporcionar cualquier información personal.",
    "The controller of your data is": "El responsable del tratamiento de tus datos es",
    ", based in Colombia. For any questions about this policy, you can contact us at": ", con domicilio en Colombia. Para cualquier consulta sobre esta política, puedes contactarnos en",
    "2. Types of Data We Collect": "2. Tipos de Datos que Recopilamos",
    "We collect and process the following categories of information when you interact with our website, the": "Recopilamos y procesamos las siguientes categorías de información cuando interactúas con nuestro sitio web, la",
    "or our services:": "o nuestros servicios:",
    "2.1 Contact Data": "2.1 Datos de Contacto",
    "Information provided through the contact form: name, email address, subject and message": "Información proporcionada a través del formulario de contacto: nombre, correo electrónico, asunto y mensaje",
    "Correspondence information when we contact you by email": "Información de la correspondencia cuando te ponemos en contacto contigo por correo electrónico",
    "2.2 Email Subscription Data": "2.2 Datos de Suscripción por Email",
    "Email address to receive our newsletter and welcome sequences": "Dirección de correo electrónico para recibir nuestro boletín y secuencias de bienvenida",
    "Subscription preferences and mailing list status": "Preferencias de suscripción y estado de la lista de distribución",
    "Email interactions (opens, clicks, replies)": "Interacciones con emails (aperturas, clics, respuestas)",
    "2.3 Usage and Activity Data": "2.3 Datos de Uso y Actividad",
    "Information about how you browse and use the website": "Información sobre cómo navegas y usas el sitio web",
    "IP addresses, browser type, operating system, language": "Direcciones IP, tipo de navegador, sistema operativo, idioma",
    "Pages visited, time on site, browsing patterns": "Páginas visitadas, tiempo de permanencia, patrones de navegación",
    "Site diagnostics and performance data": "Datos de diagnóstico y rendimiento del sitio",
    "2.4 Advertising Data": "2.4 Datos Publicitarios",
    "Information about cookies and advertising pixels used by Google AdSense and third-party ad networks": "Información de cookies y píxeles publicitarios utilizados por Google AdSense y redes publicitarias de terceros",
    "Ad interaction data (impressions, clicks)": "Datos de interacción con anuncios (impresiones, clics)",
    "Advertising ID and interest data for personalized ads": "ID de publicidad y datos de intereses para anuncios personalizados",
    "2.5 Automatically Collected Data": "2.5 Datos Recopilados Automáticamente",
    "Cookies and similar technologies (see section 7)": "Cookies y tecnologías similares (ver sección 7)",
    "Device and connection usage data": "Datos de uso del dispositivo y de la conexión",
    "Data collected by third-party services (Firebase Analytics, etc.)": "Datos recopilados por servicios de terceros (Firebase Analytics, etc.)",
    "3. Legal Basis for Data Processing": "3. Base Legal para el Tratamiento de Datos",
    "The processing of your personal information is based on the following legal grounds:": "El tratamiento de tu información personal se basa en las siguientes bases legales:",
    "Consent": "Consentimiento",
    ": When you explicitly give us permission to collect or use your data, such as when you subscribe to our newsletter or accept cookies.": ": Cuando nos das permiso explícito para recopilar o usar tus datos, como cuando te suscribes a nuestro boletín de correo electrónico o aceptas cookies.",
    "Legitimate interest": "Interés legítimo",
    ": When we use your data to improve our services, analyze site performance, personalize your experience, show relevant ads, or for security purposes.": ": Cuando utilizamos tus datos para mejorar nuestros servicios, analizar el rendimiento del sitio, personalizar tu experiencia, mostrar anuncios relevantes o para fines de seguridad.",
    "Performance of a contract": "Ejecución de un contrato",
    ": When it is necessary to provide you a requested service, such as responding to an inquiry through the contact form.": ": Cuando es necesario para prestarte un servicio solicitado, como responder a una consulta enviada a través del formulario de contacto.",
    "Legal obligation": "Obligación legal",
    ": When we are required by law to process your data, such as in compliance with tax regulations.": ": Cuando estamos obligados por ley a procesar tus datos, como en cumplimiento de normativas fiscales.",
    "4. What Do We Use Your Data For?": "4. ¿Para Qué Usamos Tus Datos?",
    "We use the information collected through the website, the": "Utilizamos la información recopilada a través del sitio web, la",
    "and our services to:": "y nuestros servicios para:",
    "Respond to your inquiries": "Responder a tus consultas",
    ": Process and respond to messages sent through the contact form.": ": Procesar y responder mensajes enviados a través del formulario de contacto.",
    "Send email communications": "Enviar comunicaciones por email",
    ": Send our newsletter, promotional content and welcome sequences (only with your consent).": ": Enviar nuestro boletín informativo, contenido promocional y secuencias de bienvenida (solo con tu consentimiento).",
    "Show personalized ads": "Mostrar anuncios personalizados",
    ": Use Google AdSense and third-party ad networks to show relevant ads based on your browsing activity.": ": Utilizar Google AdSense y redes publicitarias de terceros para mostrar anuncios relevantes basados en tu actividad de navegación.",
    "Measure advertising performance": "Medir el rendimiento publicitario",
    ": Track ad impressions, clicks and conversions to optimize our campaigns.": ": Rastrear impresiones, clics y conversiones de anuncios para optimizar nuestras campañas.",
    "Improve our services": "Mejorar nuestros servicios",
    ": Analyze usage patterns, develop new features and personalize the user experience.": ": Analizar patrones de uso, desarrollar nuevas funcionalidades y personalizar la experiencia del usuario.",
    "Security and fraud prevention": "Seguridad y prevención de fraude",
    ": Detect and prevent unauthorized access, protect the integrity of our services.": ": Detectar y prevenir accesos no autorizados, proteger la integridad de nuestros servicios.",
    "Comply with legal obligations": "Cumplir obligaciones legales",
    ": Respond to legal requirements and comply with tax and regulatory regulations.": ": Responder requerimientos legales y cumplir con normativas fiscales y regulatorias.",
    "5. Who Do We Share Your Data With": "5. Con Quiénes Compartimos Tus Datos",
    "We do not sell or rent your personal information. We only share data with third parties that help us operate our website, the": "No vendemos ni alquilamos tu información personal. Compartimos datos únicamente con terceros que nos ayudan a operar nuestro sitio web, la",
    "and our services, and that comply with strict data protection measures:": "y nuestros servicios, y que cumplen con estrictas medidas de protección de datos:",
    "5.1 Essential Service Providers": "5.1 Proveedores de Servicios Esenciales",
    ": Analysis of website and": ": Análisis de uso del sitio web y la",
    "(Analytics, Auth, Firestore). Usage data is processed on Google’s servers.": "(Analytics, Auth, Firestore). Los datos de uso se procesan en los servidores de Google.",
    "Brevo (formerly Sendinblue)": "Brevo (antes Sendinblue)",
    ": Management of email campaigns, newsletters and welcome sequences. Your contact data is stored on their servers.": ": Gestión de campañas de correo electrónico, boletines informativos y secuencias de bienvenida. Tus datos de contacto son almacenados en sus servidores.",
    "5.2 Advertising Networks (Google AdSense)": "5.2 Redes Publicitarias (Google AdSense)",
    "Our website uses": "Nuestro sitio web utiliza",
    ", an online advertising service provided by Google. Google uses cookies (including the": ", un servicio de publicidad en línea proporcionado por Google. Google utiliza cookies (incluyendo la cookie",
    ") to show personalized ads based on your browsing history on this and other websites. Google may also collect information about your visits to this site and other sites in order to show ads about products and services that may be of interest to you.": ") para mostrar anuncios personalizados basados en tu historial de navegación en este y otros sitios web. Google también puede recopilar información sobre tus visitas a este sitio y a otros sitios web con el fin de mostrar anuncios sobre productos y servicios que puedan ser de tu interés.",
    "Google, as a third-party vendor, uses cookies to show ads on our site. Google’s use of the DART cookie enables Google to show ads to users who have visited our website and other sites on the Internet. Users may opt out of the use of the DART cookie by visiting the": "Google, como proveedor externo, utiliza cookies para mostrar anuncios en nuestro sitio. El uso de la cookie DART de Google permite a Google mostrar anuncios a los usuarios que han visitado nuestro sitio web y otros sitios en Internet. Los usuarios pueden optar por no recibir el uso de la cookie DART visitando la",
    "Google privacy policy": "política de privacidad de Google",
    "and configuring ad preferences.": "y configurando las preferencias de anuncios.",
    "5.3 Technical Providers": "5.3 Proveedores Técnicos",
    "Web hosting servers.": "Servidores de alojamiento web.",
    "Analytics and usage metrics providers.": "Proveedores de análisis y métricas de uso.",
    "5.4 Legal Disclosure": "5.4 Divulgación Legal",
    "We may disclose your data if we are required by law, a court order, a government request, or to protect our rights, property or safety, or those of our users and the public.": "Podemos divulgar tus datos si estamos obligados por ley, una orden judicial, una requisición gubernamental, o para proteger nuestros derechos, propiedades o seguridad, o los de nuestros usuarios y el público.",
    "6. Third-Party Advertising and Partners": "6. Publicidad de Terceros y Partners",
    "In addition to Google AdSense, this website may use other third-party ad networks that collect information about your visits to this and other websites in order to show ads based on your interests. These providers may use:": "Además de Google AdSense, este sitio web puede utilizar otras redes publicitarias de terceros que recopilan información sobre tus visitas a este y otros sitios web con el fin de mostrar anuncios basados en tus intereses. Estos proveedores pueden utilizar:",
    ": To track your browsing activity and show personalized ads.": ": Para rastrear tu actividad de navegación y mostrar anuncios personalizados.",
    "Web beacons / pixels": "Web beacons / píxeles",
    ": To count visits, track conversions and measure ad effectiveness.": ": Para contar visitas, rastrear conversiones y medir la eficacia de anuncios.",
    "Device identifiers": "Identificadores de dispositivo",
    ": To recognize your device across different websites.": ": Para reconocer tu dispositivo entre diferentes sitios web.",
    "Interest data": "Datos de interés",
    ": To segment audiences and show relevant ads.": ": Para segmentar audiencias y mostrar anuncios relevantes.",
    "Important:": "Importante:",
    "These third parties may collect information about your activity on this website and on other websites to provide ads about products and services they think may interest you. We have no direct control over the data practices of these third-party advertising providers. We recommend reviewing the privacy policies of each ad network to learn more about their data practices and how to opt out of personalized ads.": "Estos terceros pueden recopilar información sobre tu actividad en este sitio web y en otros sitios web para proporcionar anuncios sobre productos y servicios que consideren de tu interés. No tenemos control directo sobre las prácticas de datos de estos proveedores publicitarios de terceros. Te recomendamos revisar las políticas de privacidad de cada red publicitaria para obtener más información sobre sus prácticas de datos y cómo optar por no recibir anuncios personalizados.",
    "Ads may be shown in different formats: banners, text, images or links. By clicking an ad, you may be redirected to the advertiser’s website, where their own privacy policy will apply.": "Los anuncios pueden ser mostrados en diferentes formatos: banners, texto, imágenes o enlaces. Al hacer clic en un anuncio, puedes ser redirigido al sitio web del anunciante, donde aplicará su propia política de privacidad.",
    "7. International Data Transfers": "7. Transferencias Internacionales de Datos",
    "Your data may be transferred, stored and processed on servers located in the United States or other countries outside your jurisdiction when using the website or the": "Tus datos pueden ser transferidos, almacenados y procesados en servidores ubicados en Estados Unidos u otros países fuera de tu jurisdicción al usar el sitio web o la",
    ". Firebase (Google) and Google services operate under the": ". Firebase (Google) y los servicios de Google operan bajo el",
    "EU-U.S. Data Privacy Framework": "Marco de Certificación EU-U.S. Data Privacy Framework",
    ", which ensures adequate protection for data transferred from the European Union and Switzerland. Brevo operates under the EU-US Privacy Shield framework for personal data transfers from the EU. Google AdSense processes user data on servers located in the United States in accordance with Google’s policies.": ", lo que garantiza una protección adecuada de los datos transferidos desde la Unión Europea y Suiza. Brevo opera bajo el marco EU-US Privacy Shield para transferencias de datos personales desde la UE. Google AdSense procesa datos de usuarios en servidores ubicados en Estados Unidos conforme a las políticas de Google.",
    "8. Data Retention": "8. Retención de Datos",
    "We keep your personal data for as long as necessary to fulfill the purposes described in this policy:": "Conservamos tus datos personales durante el tiempo necesario para cumplir con las finalidades descritas en esta política:",
    "Contact data:": "Datos de contacto:",
    "As long as we have a business relationship or until you request its deletion.": "Mientras mantengamos una relación comercial o hasta que solicites su eliminación.",
    "Email subscription data:": "Datos de suscripción por email:",
    "Until you withdraw your consent or request unsubscribe.": "Hasta que revoques tu consentimiento o solicites la baja.",
    "Site usage data:": "Datos de uso del sitio:",
    "Up to 30 months for statistical analysis, then anonymized.": "Hasta 30 meses para análisis estadístico, luego anonimizados.",
    "Marketing emails:": "Emails de marketing:",
    "If your account or subscription remains inactive for more than 24 months, we may proceed to delete or deactivate it.": "Si tu cuenta o suscripción permanece inactiva durante más de 24 meses, podremos proceder a su eliminación o desactivación.",
    "9. Cookies and Similar Technologies": "9. Cookies y Tecnologías Similares",
    "We use cookies and similar technologies on the website and the": "Utilizamos cookies y tecnologías similares en el sitio web y la",
    "to:": "para:",
    "Essential cookies:": "Cookies esenciales:",
    "For the operation of the website (session, authentication, language preferences).": "Para el funcionamiento del sitio web (sesión, autenticación, preferencias de idioma).",
    "Analytics cookies:": "Cookies de análisis:",
    "Firebase Analytics to understand how users interact with our website and the": "Firebase Analytics para entender cómo los usuarios interactúan con nuestro sitio web y la",
    "Advertising cookies:": "Cookies de publicidad:",
    "Google AdSense and third-party ad networks use cookies to show personalized ads, measure campaign effectiveness and avoid showing the same ads repeatedly.": "Google AdSense y redes publicitarias de terceros utilizan cookies para mostrar anuncios personalizados, medir la eficacia de las campañas y evitar mostrar los mismos anuncios repetidamente.",
    "Preference cookies:": "Cookies de preferencias:",
    "To remember your preferred language and settings.": "Para recordar tu idioma preferido y configuraciones.",
    "Marketing cookies:": "Cookies de marketing:",
    "To show relevant content and measure email campaigns (only with consent).": "Para mostrar contenido relevante y medir campañas de email (solo con consentimiento).",
    "You can manage your cookie preferences at any time through your browser settings. Keep in mind that by disabling essential cookies, parts of our website may not work correctly. You can also manage your cookie preferences with Brevo through their privacy policy.": "Puedes gestionar tus preferencias de cookies en cualquier momento a través de la configuración de tu navegador. Ten en cuenta que al desactivar las cookies esenciales, partes de nuestro sitio web pueden no funcionar correctamente. También puedes gestionar tus preferencias de cookies con Brevo a través de su política de privacidad.",
    "Opt-out option:": "Opción de exclusión voluntaria (Opt-out):",
    "You can opt out of personalized Google AdSense ads by visiting": "Puedes optar por no recibir anuncios personalizados de Google AdSense visitando la",
    "Google Ads Settings": "Configuración de anuncios de Google",
    "or downloading the": "o descargando el",
    "Google Analytics opt-out add-on": "complemento de exclusión voluntaria de Google Analytics",
    ". You can also opt out of personalized ads from other ad networks through the": ". También puedes optar por no recibir anuncios personalizados de otras redes publicitarias a través del programa",
    "or the": "o la",
    "Digital Advertising Alliance opt-out tool": "herramienta de elección de anuncios de Digital Advertising Alliance",
    "10. Your Privacy Rights (GDPR / LOPD)": "10. Tus Derechos de Privacidad (GDPR / LOPD)",
    "Depending on your jurisdiction, you have the following rights:": "Dependiendo de tu jurisdicción, tienes los siguientes derechos:",
    "Right of access:": "Derecho de acceso:",
    "Request and receive a copy of the personal data we hold about you.": "Solicitar y recibir una copia de los datos personales que tenemos sobre ti.",
    "Right to rectification:": "Derecho de rectificación:",
    "Correct inaccurate or incomplete personal data.": "Corregir datos personales inexactos o incompletos.",
    "Right to erasure:": "Derecho de supresión:",
    "Request the deletion of your personal data (\"right to be forgotten\").": "Solicitar la eliminación de tus datos personales (\"derecho al olvido\").",
    "Right to data portability:": "Derecho de portabilidad:",
    "Receive your data in a structured format and request its transfer to another controller.": "Recibir tus datos en un formato estructurado y solicitar su transferencia a otro responsable.",
    "Right to object:": "Derecho de oposición:",
    "Object to the processing of your data, especially for direct marketing and personalized advertising.": "Oponerte al tratamiento de tus datos, especialmente para fines de marketing directo y publicidad personalizada.",
    "Right to restrict processing:": "Derecho a limitar el tratamiento:",
    "Restrict the processing of your data in certain circumstances.": "Restringir el procesamiento de tus datos en ciertas circunstancias.",
    "Right not to be subject to automated decisions:": "Derecho a no ser objeto de decisiones automatizadas:",
    "Not be subject to decisions based solely on automated processing.": "No estar sujeto a decisiones basadas únicamente en procesamiento automatizado.",
    "Right to withdraw consent:": "Derecho de revocar el consentimiento:",
    "Withdraw your consent at any time without affecting the lawfulness of previous processing.": "Retirar tu consentimiento en cualquier momento sin afectar la licitud del tratamiento previo.",
    "Right to lodge a complaint:": "Derecho a presentar una reclamación:",
    "Contact your local data protection authority.": "Contactar a tu autoridad de protección de datos local.",
    "To exercise any of these rights, send a request to": "Para ejercer cualquiera de estos derechos, envía una solicitud a",
    ". We will respond within the next 30 business days. We will verify your identity before processing any request.": ". Responderemos dentro de los 30 días hábiles siguientes. Verificaremos tu identidad antes de procesar cualquier solicitud.",
    "11. California Residents' Rights (CCPA)": "11. Derechos de Residentes de California (CCPA)",
    "If you reside in California (United States), you have the following additional rights under the": "Si resides en California (Estados Unidos), tienes los siguientes derechos adicionales bajo la",
    "Right to know:": "Derecho a saber:",
    "Request the categories and specific pieces of personal data we have collected, used, disclosed and sold.": "Solicitar las categorías y las piezas específicas de datos personales que hemos recopilado, utilizado, divulgado y vendido.",
    "Right to opt out of the sale:": "Derecho a no vender:",
    "Object to the sale of your personal data to third parties. You can exercise this right by clicking": "Oponerte a la venta de tus datos personales a terceros. Puedes ejercer este derecho haciendo clic en",
    "or contacting us at": "o contactándonos en",
    "Right to deletion:": "Derecho a eliminar:",
    "Request deletion of personal data we have collected from you.": "Solicitar la eliminación de datos personales que hayamos recopilado de ti.",
    "Right not to be discriminated against:": "Derecho a no ser discriminado:",
    "We will not discriminate against you for exercising your rights under the CCPA.": "No seremos discriminados por ejercer tus derechos bajo la CCPA.",
    "This website does not sell personal data to third parties. Data collected through Firebase Analytics and Google AdSense is used solely for analytical and advertising purposes, in compliance with Google’s policies.": "Este sitio web no vende datos personales a terceros. Los datos recopilados a través de Firebase Analytics y Google AdSense se utilizan únicamente para fines analíticos y publicitarios, en cumplimiento con las políticas de Google.",
    "12. Security Measures": "12. Medidas de Seguridad",
    "We implement appropriate technical and organizational measures to protect your personal data against unauthorized access, alteration, disclosure or destruction, both on the website and in the": "Implementamos medidas técnicas y organizativas apropiadas para proteger tus datos personales contra acceso no autorizado, alteración, divulgación o destrucción, tanto en el sitio web como en la",
    ". These measures include:": ". Estas medidas incluyen:",
    "Data encryption in transit (TLS/SSL).": "Cifrado de datos en tránsito (TLS/SSL).",
    "Role-based access control for internal staff.": "Control de acceso basado en roles para el personal interno.",
    "Continuous security monitoring and intrusion detection.": "Monitoreo continuo de seguridad y detección de intrusiones.",
    "Privacy and security policies for all staff with access to data.": "Políticas de privacidad y seguridad para todo el personal con acceso a datos.",
    "Periodic risk assessments and security audits.": "Evaluaciones periódicas de riesgos y auditorías de seguridad.",
    "Please note that no method of Internet transmission or electronic storage is 100% secure. Although we strive to use commercially acceptable means to protect your information, we cannot guarantee its absolute security.": "Ten en cuenta que ningún método de transmisión por Internet o almacenamiento electrónico es 100% seguro. Aunque nos esforzamos por utilizar medios comercialmente aceptables para proteger tu información, no podemos garantizar su seguridad absoluta.",
    "12B. Data Collected in the Kore App": "12B. Datos Recopilados en la Kore App",
    "When using the": "Al usar la",
    ", we collect the following specific data:": ", recopilamos los siguientes datos específicos:",
    "12B.1 Account and Authentication Data": "12B.1 Datos de Cuenta y Autenticación",
    "Email, name and profile photo (Firebase Auth, Google Sign-In, Facebook Login)": "Correo electrónico, nombre y foto de perfil (Firebase Auth, Google Sign-In, Facebook Login)",
    "Firebase UID, authentication tokens": "UID de Firebase, tokens de autenticación",
    "12B.2 App Usage Data": "12B.2 Datos de Uso de la App",
    "Tasks, habits, notes, diary, calendar events (stored locally in Room + synced to Firestore when signed in)": "Tareas, hábitos, notas, diario, eventos de calendario (almacenados localmente en Room + sincronizados en Firestore si hay sesión)",
    "Notification, sound, vibration, language preferences (local DataStore)": "Preferencias de notificaciones, sonido, vibración, idioma (DataStore local)",
    "Premium/subscription status (Google Play Billing)": "Estado premium/suscripción (Google Play Billing)",
    "12B.3 Technical and Diagnostic Data": "12B.3 Datos Técnicos y de Diagnóstico",
    "Firebase Analytics: screen events, actions, errors, performance": "Firebase Analytics: eventos de pantalla, acciones, errores, rendimiento",
    "Firebase Crashlytics: crash reports (if enabled)": "Firebase Crashlytics: reportes de fallos (si habilitado)",
    "Device identifiers (Firebase Instance ID, Android ID)": "Identificadores de dispositivo (Firebase Instance ID, Android ID)",
    "12B.4 Notifications": "12B.4 Notificaciones",
    "FCM token for push notifications (opt-in, disabled by default)": "Token FCM para notificaciones push (opt-in, desactivado por defecto)",
    "Schedules and preferences for motivational phrases and events": "Horarios y preferencias de frases motivadoras y eventos",
    "All personal data is stored securely (TLS in transit, encrypted at rest in Firestore/Room) and you can request its deletion at any time.": "Todos los datos personales se almacenan de forma segura (TLS en tránsito, cifrado en reposo en Firestore/Room) y puedes solicitarnos su eliminación en cualquier momento.",
    "12C. Intellectual Property and Music Rights": "12C. Derechos de Propiedad Intelectual y Música",
    "All music tracks included in the Kore application are the exclusive intellectual property of": "Todas las pistas musicales incluidas en la aplicación Kore son propiedad intelectual exclusiva de",
    ". The music content was generated using artificial intelligence tools under a commercial license granted to Alquimia Lab, which gives us the necessary rights for its distribution and use in the application.": ". El contenido musical fue generado utilizando herramientas de inteligencia artificial bajo una licencia comercial otorgada a Alquimia Lab, lo que nos confiere los derechos necesarios para su distribución y uso en la aplicación.",
    "No third-party music is used without proper authorization. Track names, covers and associated information are trademarks and registered content of Alquimia Lab.": "No se utiliza música de terceros sin la debida autorización. Los nombres de las pistas, las carátulas y la información asociada son marcas y contenido registrado de Alquimia Lab.",
    "Redistribution, reproduction or commercial use of the music content is prohibited without the prior written consent of Alquimia Lab. For license or attribution requests, contact us at": "Queda prohibida la redistribución, reproducción o uso comercial del contenido musical sin el consentimiento previo y por escrito de Alquimia Lab. Para solicitudes de licencia o atribución, contactarnos en",
    "13. Minors": "13. Menores de Edad",
    "Our services are not directed at children under 16 (or the equivalent age under applicable jurisdiction). We do not knowingly collect personal information from minors. If we discover that we have collected data from a minor without parental verification, we will take steps to delete that information from our records. Parents or legal guardians can contact us at": "Nuestros servicios no están dirigidos a menores de 16 años (o la edad equivalente según la jurisdicción aplicable). No recopilamos intencionalmente información personal de menores de edad. Si descubrimos que hemos recopilado datos de un menor sin verificación parental, tomaremos medidas para eliminar dicha información de nuestros registros. Los padres o tutores legales pueden contactarnos en",
    "to request deletion of a minor's data.": "para solicitar la eliminación de datos de menores.",
    "14. Changes to this Privacy Policy": "14. Cambios a esta Política de Privacidad",
    "We may update this Privacy Policy from time to time. We will notify you of any significant change through:": "Podemos actualizar esta Política de Privacidad de vez en cuando. Te notificaremos cualquier cambio significativo a través de:",
    "A prominent banner on our website.": "Un banner destacado en nuestro sitio web.",
    "Publishing the new version with the \"Last updated\" date revised.": "Publicación de la nueva versión con la fecha de \"Última actualización\" actualizada.",
    "We recommend reviewing this policy periodically. Your continued use of our services after any change constitutes your acceptance of the new practices described.": "Te recomendamos revisar esta política periódicamente. El uso continuado de nuestros servicios después de cualquier cambio constituye tu aceptación de las nuevas prácticas descritas.",
    "15. How to Contact Us": "15. Cómo Contactarnos",
    "If you have questions, requests or concerns about this Privacy Policy or the processing of your personal data, you can contact us:": "Si tienes preguntas, solicitudes o inquietudes sobre esta Política de Privacidad o el tratamiento de tus datos personales, puedes contactarnos:",
    "Email:": "Correo electrónico:",
    "Contact form:": "Formulario de contacto:",
    "Delete Kore data:": "Eliminar datos Kore:",
    "Request data deletion": "Solicitar eliminación de datos",
    "Address:": "Domicilio:",
    "You also have the right to lodge a complaint with the data protection authority of your jurisdiction. In Colombia, you can contact the": "También tienes derecho a presentar una reclamación ante la autoridad de protección de datos de tu jurisdicción. En Colombia, puedes contactar a la",
    "Superintendency of Industry and Commerce (SIC)": "Superintendencia de Industria y Comercio (SIC)",
    "Last updated:": "Última actualización:",
    "September 21, 2026": "21 de Septiembre de 2026",
    "By using our services after the publication of any change, you accept the revised version of this Privacy Policy.": "Al utilizar nuestros servicios después de la publicación de cualquier cambio, aceptas la versión revisada de esta Política de Privacidad.",
    "Order, tranquility and autonomy for your day to day.": "Orden, Tranquilidad y Autonomía para tu día a día.",
    "Delete my data · Kore · Alquimia Lab": "Eliminar mis datos · Kore · Alquimia Lab",
    "Your calm space": "Tu espacio de calma",
    "In development": "En desarrollo",
    "Coming soon on Google Play": "Próximamente en Google Play",
    "Kore is in its final development phase. It will be your personal calm space: tasks, habits, notes, diary, relaxing music and chat with Antonio (AI).": "Kore está en fase final de desarrollo. Será tu espacio personal de calma: tareas, hábitos, notas, diario, música relajante y chat con Antonio (IA).",
    "📋 Tasks & Habits": "📋 Tareas & Hábitos",
    "📝 Notes & Diary": "📝 Notas & Diario",
    "🎵 Relaxing Music": "🎵 Música Relajante",
    "🤖 AI Chat (Antonio)": "🤖 Chat IA (Antonio)",
    "🗑️ Delete my data": "🗑️ Eliminar mis datos",
    "What gets deleted?": "¿Qué se elimina?",
    "Authentication account (Firebase Auth)": "Cuenta de autenticación (Firebase Auth)",
    "Profile data: name, email, photo": "Datos de perfil: nombre, email, foto",
    "Tasks, habits, notes, diary, events": "Tareas, hábitos, notas, diario, eventos",
    "Preferences: notifications, language, theme": "Preferencias: notificaciones, idioma, tema",
    "Chat history with Antonio (AI)": "Historial de chat con Antonio (IA)",
    "Usage and analytics data (Firebase)": "Datos de uso y analytics (Firebase)",
    "Subscription/premium status (Google Play Billing)": "Suscripción/estado premium (Google Play Billing)",
    "This action is irreversible.": "Esta acción es irreversible.",
    "Request deletion": "Solicitar eliminación",
    "Email associated with Kore *": "Email asociado a Kore *",
    "Firebase UID (optional)": "UID de Firebase (opcional)",
    "I confirm I want to permanently delete my data *": "Confirmo que quiero eliminar mis datos permanentemente *",
    "Additional message (optional)": "Mensaje adicional (opcional)",
    "🗑️ Send deletion request": "🗑️ Enviar solicitud de eliminación",
    "We will process your request within": "Procesaremos tu solicitud en",
    "30 business days": "30 días hábiles",
    "⚠️ Before sending, please note:": "⚠️ Antes de enviar, ten en cuenta:",
    "The deletion is": "La eliminación es",
    "permanent and irreversible": "permanente e irreversible",
    "You will lose access to all your tasks, habits, notes, diary, chat and music.": "Perderás acceso a todas tus tareas, hábitos, notas, diario, chat y música.",
    "Your premium subscription will be cancelled without refund.": "Tu suscripción premium se cancelará sin reembolso.",
    "Google Play billing data will be retained as required by tax law.": "Los datos de facturación de Google Play se conservan por ley fiscal.",
    "You will receive a confirmation email when it is complete.": "Recibirás email de confirmación cuando se complete.",
    "← Back to Kore": "← Volver a Kore",
    /* NAV */
    "Home": "Inicio",
    "Portfolio": "Portafolio",
    "Products": "Productos",
    "Contact": "Contacto",
    "Projects": "Proyectos",
    "About Me": "Sobre mí",
    "Work Experience": "Experiencia laboral",
    "Education": "Educación",

    /* INDEX */
    "Hi, I'm": "Hola, soy",
    "I create digital tools and designs that bring clarity and calm to your daily routine. Notion templates, coloring books, productivity tools, and visual design solutions.": "Creo herramientas digitales y diseños que aportan claridad y calma a tu rutina diaria. Plantillas de Notion, libros para colorear, herramientas de productividad y soluciones de diseño visual.",
    "View Portfolio": "Ver portafolio",
    "View Products": "Ver productos",
    "What is Alquimia Lab": "¿Qué es Alquimia Lab?",
    "Alquimia Lab is where thoughtful design meets mindful living. I craft digital sanctuaries and creative tools designed to help you quiet mental noise, organize your workflow, and embrace a calmer daily rhythm.": "Alquimia Lab es donde el diseño reflexivo se encuentra con una vida consciente. Creo santuarios digitales y herramientas creativas diseñadas para ayudarte a silenciar el ruido mental, organizar tu flujo de trabajo y adoptar un ritmo diario más calmado.",
    "Notion Templates": "Plantillas de Notion",
    "Organization systems for freelancers, planning, and personal productivity.": "Sistemas de organización para freelancers, planificación y productividad personal.",
    "Explore": "Explorar",
    "Printed Products": "Productos impresos",
    "Coloring books with a lofi aesthetic and designs that invite you to unwind.": "Libros para colorear con estética lofi y diseños que te invitan a relajarte.",
    "Digital Products": "Productos digitales",
    "Apps, planners y herramientas digitales que llevan orden con calma a tu contenido y tu día a día.": "Apps, planners y herramientas digitales que llevan orden con calma a tu contenido y tu día a día.",
    "Apps, planners, and digital tools that bring calm order to your content and daily life. Ready on desktop and mobile.": "Apps, planners y herramientas digitales que llevan orden con calma a tu contenido y tu día a día. Listas en escritorio y móvil.",
    "Explore Design Portfolio": "Explora el portafolio de diseño",
    "Bold brand identities, intuitive UI/UX, and social media visuals crafted to captivate.": "Identidades de marca audaces, UI/UX intuitivos y visuales para redes sociales creados para cautivar.",
    "Featured": "Destacados",
    "Operating system to structure your workflow from start to finish.": "Sistema operativo para estructurar tu flujo de trabajo de principio a fin.",
    "Available in Free and Pro versions.": "Disponible en versiones Free y Pro.",
    "Clear mental noise and protect your energy with a minimalist sanctuary.": "Silencia el ruido mental y protege tu energía con un santuario minimalista.",
    "Comprehensive Notion workspace for creators and producers.": "Espacio de trabajo integral de Notion para creadores y productores.",
    "A minimalist ecosystem for creators and entrepreneurs.": "Un ecosistema minimalista para creadores y emprendedores.",
    "Coloring Books": "Libros para colorear",
    "Print edition on Amazon and digital on Gumroad.": "Edición impresa en Amazon y digital en Gumroad.",
    "Get it": "Conseguir",
    "Explore all products": "Explorar todos los productos",
    "© 2026 Alquimia Lab · Made with calm & coffee": "© 2026 Alquimia Lab · Hecho con calma y café",

    /* PORTAFOLIO */
    "Graphic Designer & Visual Content Curator": "Diseñadora Gráfica y Curadora de Contenido Visual",
    "Hi! I'm Isabel Boder, a 30-year-old passionate graphic designer. I thrive in both collaborative and independent environments, bringing a strong sense of responsibility and discipline to successfully tackle every project.": "¡Hola! Soy Isabel Boder, una apasionada diseñadora gráfica de 30 años. Me desenvuelvo bien tanto en entornos colaborativos como independientes, aportando un fuerte sentido de responsabilidad y disciplina para afrontar con éxito cada proyecto.",
    "In the fast-paced world of design, I believe in staying curious, continuously learning, and keeping up with the latest tools, trends, and creative strategies. I'm committed to growing every day to consistently deliver work that exceeds expectations.": "En el vertiginoso mundo del diseño, creo en mantener la curiosidad, aprender continuamente y estar al día con las últimas herramientas, tendencias y estrategias creativas. Estoy comprometida a crecer cada día para entregar siempre un trabajo que supere las expectativas.",
    "Skills": "Habilidades",
    "Time Management": "Gestión del Tiempo",
    "Planning": "Planificación",
    "Teamwork": "Trabajo en Equipo",
    "Communication": "Comunicación",
    "Tools": "Herramientas",
    "2023 — Now": "2023 — Actualidad",
    "Visual Content Curator": "Curadora de Contenido Visual",
    "Select and evaluate graphic resources (vectors & photos) for publishing on Freepik.com": "Seleccionar y evaluar recursos gráficos (vectores y fotos) para su publicación en Freepik.com",
    "Freelance Designer": "Diseñadora Freelance",
    "Various clients (Ongoing)": "Varios clientes (en curso)",
    "Branding, digital content, and visual design for web and social media": "Branding, contenido digital y diseño visual para web y redes sociales",
    "Digital Graphic Designer": "Diseñadora Gráfica Digital",
    "Created short animations in After Effects. Developed branding, visual identity, and social media layouts. Designed websites in Figma, including structure and sitemap. Created digital catalogs and print pieces: billboards, photo calls, flyers, stationery.": "Creé animaciones cortas en After Effects. Desarrollé branding, identidad visual y piezas para redes sociales. Diseñé sitios web en Figma, incluyendo estructura y mapa del sitio. Creé catálogos digitales y piezas impresas: vallas, photocalls, volantes y papelería.",
    "La Company — Advertising Agency": "La Company — Agencia de Publicidad",
    "Graphic Design Intern": "Practicante de Diseño Gráfico",
    "Created mailings, banners for Instagram & Facebook. Edited short videos and photo content. Designed and laid out the full real estate magazine EME.": "Creé mailings y banners para Instagram y Facebook. Edité videos cortos y contenido fotográfico. Diseñé y maqueté la revista inmobiliaria completa EME.",
    "Graphic Designer": "Diseñadora Gráfica",
    "Updated the brand using the newly designed logo. Designed learning books to help improve Spanish skills. Handled the design and layout of the website: www.blinkspanish.com": "Actualicé la marca usando el nuevo logo diseñado. Diseñé libros de aprendizaje para ayudar a mejorar el español. Me encargué del diseño y maquetación del sitio web: www.blinkspanish.com",
    "Associate Degree in Graphic Design Management": "Tecnología en Gestión del Diseño Gráfico",
    "Bachelor's Degree in Graphic Design": "Licenciatura en Diseño Gráfico",
    "UI/UX Design Certificate": "Certificado en Diseño UI/UX",
    "User Research": "Investigación de Usuarios",
    "Certifications": "Certificaciones",
    "Credential ID: 9jeajmszyggp": "ID de credencial: 9jeajmszyggp",
    "Credential ID: tdreqsssjkra": "ID de credencial: tdreqsssjkra",
    "Credential ID: 2n6z7wwujeow": "ID de credencial: 2n6z7wwujeow",
    "Services": "Servicios",
    "Creation of unique brand identities, including logos, visual systems, and brand guidelines.": "Creación de identidades de marca únicas, incluyendo logos, sistemas visuales y guías de marca.",
    "UI/UX Design": "Diseño UI/UX",
    "Design of intuitive and user-centered digital experiences, including user research, wireframing, interface design, and interactive prototyping.": "Diseño de experiencias digitales intuitivas y centradas en el usuario, incluyendo investigación de usuarios, wireframes, diseño de interfaz y prototipado interactivo.",
    "Social Media Design": "Diseño para Redes Sociales",
    "Creation of engaging social media visuals, campaign graphics, post templates, and story designs that help brands connect with their audience online.": "Creación de visuales atractivos para redes sociales, gráficas de campañas, plantillas de publicaciones y diseños de historias que ayudan a las marcas a conectar con su audiencia en línea.",
    "Visual Design": "Diseño Visual",
    "Development of creative visual assets including editorial design, packaging, illustrations, and motion graphics for digital and print media.": "Desarrollo de piezas visuales creativas, incluyendo diseño editorial, empaques, ilustraciones y motion graphics para medios digitales e impresos.",
    "Social Media": "Redes Sociales",
    "Illustration": "Ilustración",
    "Print & Packaging": "Impreso y Empaques",
    "Character": "Personaje",
    "View project": "Ver",
    "Brand Identity Exploration": "Exploración de Identidad de Marca",
    "User Experience Design": "Diseño de Experiencia de Usuario",
    "Social Media Campaign": "Campaña de Redes Sociales",
    "Creative Illustration": "Ilustración Creativa",
    "Packaging & Editorial": "Empaques y Editorial",
    "AI Characters": "Personajes IA",
    "Packaging": "Empaques",
    "Editorial": "Editorial",

    /* UX */
    "← Back to Portfolio": "← Volver al portafolio",
    "USER EXPERIENCE DESIGN": "DISEÑO DE EXPERIENCIA DE USUARIO",
    "Landing pages and a mobile app designed with a focus on usability, clarity, and delightful interactions.": "Landing pages y una app móvil diseñadas con foco en la usabilidad, la claridad e interacciones agradables.",
    "Tap on each project to preview it.": "Toca cada proyecto para previsualizarlo.",
    "This design was a practice piece — not created for a client.": "Este diseño fue una pieza de práctica, no fue creado para un cliente.",
    "Open in Figma": "Abrir en Figma",

    /* SOCIAL */
    "SOCIAL MEDIA CAMPAIGN": "CAMPAÑA DE REDES SOCIALES",
    "Social media visuals designed to boost engagement and give each brand a recognizable, cohesive voice online.": "Visuales para redes sociales diseñados para potenciar la interacción y darle a cada marca una voz reconocible y coherente en línea.",
    "Tap on each campaign to browse its posts.": "Toca cada campaña para revisar sus publicaciones.",
    "Liked by alquimia.lab8": "Le gusta a alquimia.lab8",

    /* AI CHARACTERS */
    "AI CHARACTERS": "PERSONAJES IA",
    "Original characters designed with artificial intelligence, each with its own personality.": "Personajes originales diseñados con inteligencia artificial, cada uno con su propia personalidad.",
    "Tap a character to open their profile.": "Toca un personaje para abrir su perfil.",
    "Eduardo is an enigmatic otherworldly creature who, despite his terrifying appearance, is a sweet and sensitive soul with a huge heart. Passionate about drama, darkness, and true crime, he has an insatiable curiosity for investigating criminal cases, perfectly balancing a dark aesthetic with a surprisingly warm and gentle personality.": "Eduardo es una criatura enigmática de otro mundo que, a pesar de su apariencia aterradora, es un alma dulce y sensible de gran corazón. Apasionado por el drama, la oscuridad y el true crime, siente una curiosidad insaciable por investigar casos criminales, equilibrando a la perfección una estética oscura con una personalidad sorprendentemente cálida y gentil.",
    "Antonio is an endearingly shy red panda with a clumsy charm and a deep passion for creativity and continuous learning. He adores everything cozy and peaceful that brings a sense of calm. While he isn't the most outgoing soul, he treats his small inner circle like true family.": "Antonio es un panda rojo adorablemente tímido, con un encanto torpe y una profunda pasión por la creatividad y el aprendizaje continuo. Adora todo lo acogedor y pacífico que aporta sensación de calma. Aunque no es el alma más sociable, trata a su pequeño círculo cercano como una verdadera familia.",

    /* BRANDING */
    "BRAND IDENTITY EXPLORATION": "EXPLORACIÓN DE IDENTIDAD DE MARCA",
    "A selection of logo designs developed to capture the essence of each brand through clean, adaptable, and impactful visuals.": "Una selección de diseños de logo desarrollados para capturar la esencia de cada marca a través de visuales limpias, adaptables e impactantes.",
    "Tap on each logo to view the complete brand board.": "Toca cada logo para ver el brand board completo.",
    "Color Palette": "Paleta de Colores",
    "Typography": "Tipografía",
    "Primary / Headline": "Primaria / Titular",
    "Secondary / Body": "Secundaria / Cuerpo",

    /* PRODUCTOS */
    "My Products": "Mis Productos",
    "Tools and creativity to organize your life, find calm, and work with intention.": "Herramientas y creatividad para organizar tu vida, encontrar calma y trabajar con intención.",
    "My Lofi Music": "Mi Música Lofi",
    "Subscribe on YouTube →": "Suscríbete en YouTube →",
    "Productivity, planning, and personal & professional organization systems. 7 templates available.": "Sistemas de productividad, planificación y organización personal y profesional. 7 plantillas disponibles.",
    "View all": "Ver todo",
    "Coloring books, productivity PDFs, and more. Available on Amazon and Gumroad.": "Libros para colorear, PDFs de productividad y más. Disponibles en Amazon y Gumroad.",
    "Digital Products": "Productos digitales",
    "Apps, planners, and digital tools that bring calm order to your content and daily life. Ready on desktop and mobile.": "Apps, planners y herramientas digitales que llevan orden con calma a tu contenido y a tu día a día. Listas en escritorio y móvil.",
    "Plan Maestro Template": "Plantilla Plan Maestro",
    "Blank content plan for pillars, calendar, copy, ideas, and multiple brands. No more messy spreadsheets.": "Plan de contenido en blanco con pilares, calendario, copys, ideas y varias marcas. Adiós a las hojas de cálculo desordenadas.",
    "Five interactive planners in one place: calm, annual, ADHD, menstrual, and weekly. Dark mode, favorites, and PDF export.": "Cinco planners interactivos en un solo lugar: calma, anual, TDAH, menstrual y semanal. Modo oscuro, favoritos y exportación a PDF.",
    "Pet Control — Notion Template": "Control de Mascotas — Plantilla Notion",
    "Vaccines, vet visits, meds, and food in one dashboard. Never miss a rabies shot again.": "Vacunas, citas, medicamentos y alimento en un solo dashboard. Nunca olvides una antirrábica otra vez.",
    "Coming soon": "Próximamente",
    "← Back": "← Volver",
    "Organize your personal finances with a visual and intuitive system.": "Organiza tus finanzas personales con un sistema visual e intuitivo.",
    "Advanced financial tracking with detailed reports and projections.": "Seguimiento financiero avanzado con informes detallados y proyecciones.",
    "Transform your habits without the visual guilt of missed days from the past. A clean-slate design to keep your mind clear and focused entirely on your growth.": "Transforma tus hábitos sin la culpa visual de los días perdidos del pasado. Un diseño de hoja en blanco para mantener tu mente clara y enfocada por completo en tu crecimiento.",
    "Say goodbye to scattered notes and missed deadlines with a single minimalist dashboard. Run your entire student life smoothly, from daily tasks to final exams.": "Di adiós a las notas dispersas y a los plazos perdidos con un único dashboard minimalista. Lleva toda tu vida estudiantil sin contratiempos, desde las tareas diarias hasta los exámenes finales.",
    "Free your mind from mental noise with a minimalist sanctuary designed to protect your energy and bring calm. Transform your daily routines into a gentle daily flow of intentional reflection.": "Libera tu mente del ruido mental con un santuario minimalista diseñado para proteger tu energía y traer calma. Transforma tus rutinas diarias en un flujo suave de reflexión intencional.",
    "Stop losing video ideas with a comprehensive Notion workspace built for creators and producers. Bring strategic clarity to your channel, from long-form scripts to viral shorts.": "Deja de perder ideas de video con un espacio de trabajo integral de Notion creado para creadores y productores. Lleva claridad estratégica a tu canal, desde guiones largos hasta shorts virales.",
    "Bring mental clarity and absolute control to your digital business with a minimalist ecosystem designed for creators and entrepreneurs. Manage everything seamlessly in one aesthetic place.": "Lleva claridad mental y control absoluto a tu negocio digital con un ecosistema minimalista diseñado para creadores y emprendedores. Gestiona todo sin esfuerzo en un solo lugar estético.",
    "Buy": "Comprar",
    "Download": "Descargar",
    "Your Notion isn't broken. It's just poorly designed. 43-page protocol.": "Tu Notion no está roto. Solo está mal diseñado. Protocolo de 43 páginas.",
    "Coloring Books — Lofi Coloring": "Libros para Colorear — Lofi Coloring",
    "Same book in English and Spanish. Print and digital edition.": "Mismo libro en inglés y español. Edición impresa y digital.",
    "We're working on it…": "Lo estamos trabajando…",
    "Soon": "Pronto",
    "Soon on Amazon": "Pronto en Amazon",
    "On Amazon": "En Amazon",
    "A minimalist planner to organize your year with calm and intention.": "Un planificador minimalista para organizar tu año con calma e intención.",
    "Planner 2027": "Planificador 2027",
    "🔒 Secure checkout on Amazon & Gumroad": "🔒 Compra segura en Amazon y Gumroad",
    "Which one is for you?": "¿Cuál es para ti?",
    "Pick your chaos:": "Elige tu caos:",
    "My admin life is chaos": "Mi vida administrativa es un caos",
    "I want calm and order": "Quiero calma y orden",
    "I relax by coloring": "Me relajo coloreando",
    "I want a paper planner": "Quiero un planner en papel",

    /* TIENDA / NUEVA PÁGINA DE PRODUCTOS */
    "The whole shop 🛍️": "La tienda completa 🛍️",
    "All products": "Todos los productos",
    "Templates, planners, books, and digital tools — all in one place, made with calm.": "Plantillas, planners, libros y herramientas digitales — todo en un solo lugar, hecho con calma.",
    "See products ↓": "Ver productos ↓",
    "All ✨": "Todo ✨",
    "Try online": "Probar online",
    "NEW": "NUEVO",
    "Tap a category to filter — or keep it on All and browse everything 😊": "Toca una categoría para filtrar — o déjalo en Todo y mira todo 😊",
    "The real story of my leap into the freelance life — with 15 prompts to copy and paste, exercises with space to write, and a launch checklist. Coming very soon.": "La historia real de mi salto a la vida freelance — con 15 prompts para copiar y pegar, ejercicios con espacio para escribir y un checklist de lanzamiento. Muy pronto.",
    "Vaccines, vet visits, meds, and food in one dashboard. For Bonnie, Luna and every fur baby.": "Vacunas, veterinario, medicinas y comida en un solo dashboard. Para Bonnie, Luna y todos los peluditos.",
    "Notify me when it launches 🔔": "Avísame cuando salga 🔔",
    "Browse categories ↓": "Ver categorías ↓",
    "The leap into freelance life, told without filters.": "El salto a la vida freelance, contado sin filtro.",
    "The real story of my leap into the freelance life — with 15 prompts to copy and paste, exercises with space to write, and a launch checklist.": "La historia real de mi salto a la vida freelance — con 15 prompts para copiar y pegar, ejercicios con espacio para escribir y un checklist de lanzamiento.",
    "Planner 2027 — Calma y Orden": "Planificador 2027 — Calma y Orden",
    "© 2026 Alquimia Lab · Made with calm & coffee ·": "© 2026 Alquimia Lab · Hecho con calma y café ·",
    "Your image here ✨": "Tu imagen aquí ✨",
    "Digital tools for calm days": "Herramientas digitales para días con calma",
    "Planners and dashboards that bring order to your content and your day.": "Planners y dashboards que ordenan tu contenido y tu día.",
    "Shop digital →": "Ver digitales →",
    "Your life, organized in one place": "Tu vida, organizada en un solo lugar",
    "CRM, finance, habits, student and creator systems — ready in seconds.": "Sistemas de CRM, finanzas, hábitos, estudiante y creadoras — listos en segundos.",
    "Shop templates →": "Ver plantillas →",
    "Color, plan, unwind on paper": "Colorea, planea y descansa en papel",
    "Coloring books and the 2027 planner — print or digital edition.": "Libros para colorear y el planner 2027 — edición impresa o digital.",
    "Shop printed →": "Ver impresos →",
    "From $3": "Desde $3",
    "7 templates": "7 plantillas",
    "From $12.99": "Desde $12.99",

    /* PRODUCTOS · MODAL JOURNAL + INDEX */
    "Calma y Orden — Hybrid Journal for Self-Care & Productivity": "Calma y Orden — Journal Híbrido de Autocuidado y Productividad",
    "What you'll find inside": "Lo que encontrarás dentro",
    "Vaccines, vet visits, meds, and food in one dashboard. Never miss a rabies shot again — built for Bonnie, Luna, and every fur baby.": "Vacunas, citas, medicamentos y alimento en un solo dashboard. Nunca olvides una antirrábica — para Bonnie, Luna y todos los peluditos.",
    "Join me 💜": "Unirme 💜",
    "Loading...": "Cargando...",
    "Thank you! 💜": "¡Gracias! 💜",
    "Done! Check your inbox to confirm": "¡Listo! Revisa tu correo para confirmar",

    /* SALES · PLANNER 2027 */
    "Print edition · 2027": "Edición impresa · 2027",
    "Calma y Orden —": "Calma y Orden —",
    "A minimalist hybrid journal for self-care and productivity. Organize your responsibilities and your calm in one beautiful place.": "Un journal híbrido minimalista de autocuidado y productividad. Organiza tus responsabilidades y tu calma en un solo lugar hermoso.",
    "Buy on Amazon": "Comprar en Amazon",
    "Digital version": "Versión digital",
    "Secure checkout · Protected by Amazon's return policy": "Compra segura · Protegida por la política de devoluciones de Amazon",
    "Made for you if…": "Hecho para ti si…",
    "🌪️ You live in chaos and need one place for tasks, habits, money, and mind.": "🌪️ Vives en el caos y necesitas un solo lugar para tareas, hábitos, dinero y mente.",
    "💜 Classic planners bore you — you want self-care built in, not as an afterthought.": "💜 Los planners clásicos te aburren — quieres autocuidado integrado, no como añadido.",
    "✍️ You love paper — writing by hand helps you think and remember.": "✍️ Amas el papel — escribir a mano te ayuda a pensar y recordar.",
    "🍃 You want calm, not pressure — no guilt trips, just gentle structure.": "🍃 Quieres calma, no presión — sin culpas, solo estructura amable.",
    "Inside the planner": "Dentro del planner",
    "Monthly calendars": "Calendarios mensuales",
    "with space for key dates and monthly goals.": "con espacio para fechas clave y objetivos del mes.",
    "Weekly planning": "Planificación semanal",
    "combining responsibilities + mandatory self-care.": "que combina responsabilidades + autocuidado obligatorio.",
    "Daily pages": "Páginas diarias",
    "with to-do lists and rotating reflection prompts.": "con listas de tareas y prompts de reflexión rotativos.",
    "Monthly habit tracker": "Tracker de hábitos mensual",
    "— 31-day × 6-habit grid.": "— grilla de 31 días × 6 hábitos.",
    "Personal finance control": "Control de finanzas personales",
    "(income, expenses, savings, balance).": "(ingresos, gastos, ahorro y balance).",
    "Energy & stress log": "Registro de energía y estrés",
    "to spot your patterns.": "para identificar tus patrones.",
    "Free spaces": "Espacios libres",
    "for notes, ideas, and mental downloads.": "para notas, ideas y descarga mental.",
    "Year-end closing page": "Página de cierre anual",
    "to reflect on your growth.": "para reflexionar sobre tu crecimiento.",
    "Get yours": "Consigue el tuyo",
    "Print edition": "Edición impresa",
    "Softcover, delivered to your door by Amazon.": "Tapa blanda, entregado en tu puerta por Amazon.",
    "Digital edition": "Edición digital",
    "Instant download to print or use on your tablet.": "Descarga instantánea para imprimir o usar en tu tableta.",
    "Get digital": "Obtener digital",
    "Is it physical or digital?": "¿Es físico o digital?",
    "Both! The print edition (paperback) ships via Amazon, and the digital edition downloads instantly from Gumroad for tablets or home printing.": "¡Ambos! La edición impresa (tapa blanda) llega vía Amazon, y la digital se descarga al instante desde Gumroad para tableta o impresión en casa.",
    "What if I don't like it?": "¿Y si no me gusta?",
    "Amazon covers print orders with easy returns, and Gumroad covers digital ones. You buy protected.": "Amazon cubre los pedidos impresos con devoluciones fáciles, y Gumroad los digitales. Compras protegida.",
    "Do I need experience with planners?": "¿Necesito experiencia con planners?",
    "None. Every section guides you — just open it and start where you are today.": "Ninguna. Cada sección te guía — solo ábrelo y empieza donde estás hoy.",
    "Your calm 2027 starts here": "Tu calma 2027 empieza aquí",
    "One planner. Your tasks, your habits, your money, your mind — in order.": "Un planner. Tus tareas, tus hábitos, tu dinero, tu mente — en orden.",

    /* CONTACTO */
    "Shall we work together?": "¿Trabajamos juntos?",
    "Tell me about your project and let's create something amazing together.": "Cuéntame sobre tu proyecto y creemos algo increíble juntos.",
    "Send message →": "Enviar mensaje →",

    /* KORE LANDING */
    "Coming soon · by Alquimia Lab": "Muy pronto · por Alquimia Lab",
    "Your space of calm": "Tu espacio de calma",
    ", in an app": ", en una app",
    "Your space of calm, in an app": "Tu espacio de calma, en una app",
    "Your calm space: tasks, habits, notes, diary, lo‑fi music and an AI assistant — all in one app.": "Tu espacio de calma: tareas, hábitos, notas, diario, música lo‑fi y un asistente con IA — todo en una sola app.",
    "Kore is your calm space: tasks, habits, notes, diary, lo‑fi music and an AI assistant — all in one app.": "Kore es tu espacio de calma: tareas, hábitos, notas, diario, música lo‑fi y un asistente con IA — todo en una sola app.",
    "Notify me when it launches": "Avísame cuando salga",
    "Notify me": "Avísame",
    "View modules": "Ver módulos",
    "Android · Coming soon": "Android · Muy pronto",
    "Spaces in 1 app": "Espacios en 1 app",
    "Lo‑fi music": "Música lo‑fi",
    "AI assistant": "Asistente IA",
    "No complicated menus. No 40 buttons. Open, breathe, organize.": "Sin menús complicados. Sin 40 botones. Abres, respiras, organizas.",
    "The problem": "El problema",
    "Does this sound familiar?": "¿Te suena esto?",
    "Kore was born from real chaos. If any of this resonates, it's for you.": "Kore nació de un caos real. Si te identificas con alguno, es para ti.",
    "Tasks everywhere": "Tareas regadas",
    "Notes, WhatsApp, your head… nothing in one place.": "Notas, WhatsApp, mental… nada en un solo lugar.",
    "Habits you quit": "Hábitos que abandonas",
    "By week one they fall apart and you start from zero.": "A la semana se caen y vuelves a empezar de 0.",
    "Racing thoughts": "Pensamientos que rondan",
    "Ideas and feelings with nowhere to go.": "Ideas y emociones sin dónde soltarlas.",
    "Mental noise": "Ruido mental",
    "Your mind won't stop and focus feels impossible.": "La cabeza no para y cuesta concentrarte.",
    "Feeling alone": "Sentirte sola",
    "Doubts with no one to talk them through.": "Dudas sin con quién conversarlas.",
    "The story": "La historia",
    "Why Kore?": "¿Por qué Kore?",
    "Kore was born from a personal need: finding calm in the middle of chaos. Its creator wanted one app to order her day and care for her mind — since it didn't exist, she built it.": "Kore nació de una necesidad personal: encontrar calma en medio del caos. Su creadora quería una sola app que ordenara su día y cuidara su mente — como no existía, la construyó.",
    "In Ancient Greek, Kore (κόρη) means “maiden”: the name of Persephone as goddess of spring — a symbol of rebirth and starting anew.": "En griego antiguo, Kore (κόρη) significa «doncella»: es el nombre de Perséfone como diosa de la primavera, símbolo de renacer y empezar de nuevo.",
    "Kore is that: your daily rebirth, your space to come back to yourself.": "Kore es eso: tu renacer diario, tu espacio para volver a ti.",
    "The modules": "Los módulos",
    "Everything Kore brings": "Todo lo que trae Kore",
    "Kore is your daily companion for order and peace. Organize your tasks, build habits that last, write how you feel in your diary, save ideas in notes, and calm your mind with lo‑fi music. And when you need to talk, Antonio, your AI assistant, is there for you. No distractions, no noise — just you and your calm.": "Kore es tu compañera diaria de orden y tranquilidad. Organiza tus tareas, construye hábitos que sí duran, escribe lo que sientes en tu diario, guarda tus ideas en notas y calma tu mente con música lo‑fi. Y cuando necesites hablar, Antonio, tu asistente con IA, está ahí para acompañarte. Sin distracciones, sin ruido: solo tú y tu calma.",
    "Drag or use the arrows →": "Arrastra o usa las flechas →",
    "Tasks": "Tareas",
    "Write what's pending, check it off, feel the peace of that check ✔": "Escribe lo pendiente, táchalo, siente la paz del check ✔",
    "Habits": "Hábitos",
    "Pick your habits, mark them daily, watch your streak grow 🔥": "Elige tus hábitos, márcalos cada día, mira tu racha crecer 🔥",
    "Notes": "Notas",
    "Quick ideas, lists and reminders in seconds": "Ideas rápidas, listas y recordatorios en segundos",
    "Diary": "Diario",
    "How do you feel today? Saved just for you 🔒": "¿Cómo te sientes hoy? Guardado solo para ti 🔒",
    "Hit play and calm your mind instantly": "Dale play y calma tu mente al instante",
    "Antonio (AI)": "Antonio (IA)",
    "Ask him anything — here for you 24/7": "Pregúntale lo que sea, te acompaña 24/7",
    "This is what opening Kore feels like": "Así se siente abrir Kore",
    "A real look at the app: tasks, habits, diary and your daily calm. No filters, no weird promises — just the interface.": "Un vistazo real a la app: tareas, hábitos, diario y tu calma del día. Sin filtros, sin promesas raras — solo la interfaz.",
    "🌅 Rituals": "🌅 Rituales",
    "📋 Tasks": "📋 Tareas",
    "🌱 Habits": "🌱 Hábitos",
    "📖 Diary": "📖 Diario",
    "🤖 Antonio": "🤖 Antonio",
    "Pricing": "Precios",
    "Start free. Go Premium whenever you want to unlock everything.": "Empieza gratis. Pasa a Premium cuando quieras desbloquear todo.",
    "Feature": "Función",
    "Free": "Gratis",
    "Premium": "Premium",
    "Free vs Premium": "Gratis vs Premium",
    "FAQ": "Preguntas frecuentes",
    "Privacy Policy": "Política de Privacidad",
    "Links": "Enlaces",
    "Social": "Redes",
    "Unlimited tasks": "Ilimitadas",
    "✅ Unlimited tasks": "✅ Ilimitadas",
    "Up to 3": "Hasta 3",
    "Unlimited habits": "Ilimitados",
    "♾️ Unlimited habits": "♾️ Ilimitados",
    "Notes & diary": "Notas y diario",
    "Up to 20": "Hasta 20",
    "Up to 20 active": "Hasta 20 activas",
    "Diary": "Diario",
    "Notes": "Notas",
    "♾️ Unlimited": "♾️ Ilimitado",
    "Unlimited + styles": "Ilimitados + estilos",
    "♾️ Unlimited + styles": "♾️ Ilimitados + estilos",
    "2 playlists": "2 playlists",
    "3 playlists": "3 playlists",
    "Unlimited lo‑fi": "Lo‑fi ilimitado",
    "♾️ Unlimited lo‑fi": "♾️ Lo‑fi ilimitado",
    "Chat with Antonio (AI)": "Chat con Antonio (IA)",
    "5 messages": "5 mensajes",
    "5 messages/day": "5 mensajes/día",
    "Unlimited chat": "Ilimitado",
    "♾️ Unlimited chat": "♾️ Ilimitado",
    "Languages": "Idiomas",
    "Spanish & English": "Español e inglés",
    "All 9 languages": "Los 9 idiomas",
    "Free trial": "Prueba gratis",
    "7 days free": "7 días gratis",
    "Monthly": "Mensual",
    "per month": "por mes",
    "Most popular": "Más popular",
    "Yearly": "Anual",
    "per year · save": "por año · ahorras",
    "Questions": "Preguntas",
    "Is it free?": "¿Es gratis?",
    "Yes. Kore is free to start your daily system. Optional premium features come later — the base will always be free.": "Sí. Kore es gratis para empezar tu sistema diario. Funciones premium opcionales llegarán después — la base siempre será gratuita.",
    "Do I need to use it every day?": "¿Necesito usarlo todos los días?",
    "No guilt here. Miss a day? Come back the next. The tracker shows real progress — not a streak that stresses you out.": "No hay culpa aquí. Si fallas un día, vuelves al siguiente. El tracker te muestra el progreso real, no un streak que te estrese.",
    "Does it work if I have ADHD or anxiety?": "¿Sirve si tengo TDAH o ansiedad?",
    "It was designed with that brain in mind: few decisions, clear rituals, zero scolding. It doesn't replace therapy — it supports your system.": "Fue diseñado con ese cerebro en mente: pocas decisiones, rituales claros, cero regaños. No reemplaza terapia — acompaña tu sistema.",
    "When does it launch?": "¿Cuándo sale?",
    "Very soon. Leave your email or follow us on Instagram @alquimia.lab8 and we'll notify you on launch day.": "Muy pronto. Déjanos tu correo o síguenos en Instagram @alquimia.lab8 y te avisamos el día del lanzamiento.",
    "Who made Kore?": "¿Quién hizo Kore?",
    "Alquimia Lab — Isabel. Product designer with 6 years creating order systems for real people.": "Alquimia Lab — Isabel. Diseñadora de producto con 6 años creando sistemas de orden para personas reales.",
    "🔔 Notify me when it launches": "🔔 Avísame cuando salga",
    "We'll email you on launch day. No spam — just the news.": "Te escribimos el día del lanzamiento. Sin spam, solo la noticia.",
    "Or follow us on": "O síguenos en",
    "Want to delete your data?": "¿Deseas eliminar tus datos?",
    "Do you want to delete your Kore data?": "¿Deseas eliminar tus datos de Kore?",
    "Delete my data": "Eliminar mis datos",
    "Kore App": "App Kore",
    "Android · Coming soon on Google Play": "Android · Próximamente en Google Play",
    "View Kore →": "Ver Kore →",
    "Order, Calm and Autonomy for your day to day.": "Orden, Tranquilidad y Autonomía para tu día a día.",

    /* HOME V2 */
    "Alquimia Lab · design with calm": "Alquimia Lab · diseño con calma",
    "Meet Isabel": "Conoce a Isabel",
    "Hi, I'm": "Hola, soy",
    "Get calm in your inbox": "Recibe calma en tu correo",
    "Launches, news, and early access to Kore. No spam, only the good stuff.": "Lanzamientos, novedades y acceso anticipado a Kore. Sin spam, solo lo bueno.",
    "Join": "Unirme",
    "You're in! Check your inbox 💜": "¡Listo! Revisa tu bandeja 💜",
    "I'm a graphic designer and creator of Alquimia Lab — where thoughtful design meets a conscious life. I create digital sanctuaries and creative tools that help you quiet the mental noise, organize your workflow, and live at a calmer pace.": "Soy diseñadora gráfica y creadora de Alquimia Lab — donde el diseño reflexivo se encuentra con una vida consciente. Creo santuarios digitales y herramientas creativas que te ayudan a silenciar el ruido mental, organizar tu flujo de trabajo y vivir a un ritmo más calmado.",
    "Notion templates, coloring books, planners, and soon": "Plantillas de Notion, libros para colorear, planners y pronto",
    "— my app of calm. Everything I make comes from my own need for order without rigidity.": "— mi app de calma. Todo lo que hago nace de mi propia necesidad de orden sin rigidez.",
    "About me": "Sobre mí",
    "Let's talk": "Hablemos",
    "Selected Work": "Trabajo seleccionado",
    "View full portfolio →": "Ver portafolio completo →",
    "Apps, planners and digital tools that bring calm order to your day.": "Apps, planners y herramientas digitales que llevan orden con calma a tu día.",
    "Branding, UI/UX, illustration and visual design for conscious brands.": "Branding, UI/UX, ilustración y diseño visual para marcas conscientes.",
    "The soundtrack of your calm": "La banda sonora de tu calma",
    "15 mixes for studying, working, and breathing for a while. Made with calm by Alquimia Lab.": "15 mezclas para estudiar, trabajar y respirar un rato. Hechas con calma por Alquimia Lab.",
    "Listen on YouTube →": "Escúchanos en YouTube →",
    "Free your mind from mental noise with a minimalist sanctuary designed to protect your energy and bring calm.": "Libera tu mente del ruido mental con un santuario minimalista diseñado para proteger tu energía y traer calma.",
    "View": "Ver",
    "Social media visuals designed to boost engagement and give each brand a recognizable voice.": "Visuales para redes sociales diseñados para potenciar la interacción y darle a cada marca una voz reconocible.",
    "Stop losing video ideas with a comprehensive Notion workspace built for creators.": "Deja de perder ideas de video con un espacio de trabajo integral de Notion para creadores.",
    "Free your mind from mental noise with a minimalist sanctuary.": "Libera tu mente del ruido mental con un santuario minimalista.",
    "Social media visuals designed to boost engagement.": "Visuales para redes sociales diseñados para potenciar la interacción.",
    "Stop losing video ideas with a comprehensive Notion workspace.": "Deja de perder ideas de video con un espacio de trabajo integral de Notion.",
    "What they say": "Lo que dicen",
    "I wanted to thank you for the help with my personal branding — I got great reception on the posts. I've shared your work and sent you as a reference in a group of developers. Someone mentioned they'd write to you.": "Quería agradecerte la ayuda con mi branding personal — tuvo muy buena acogida en las publicaciones. He compartido tu trabajo y te mandé como referencia en un grupo de desarrolladores. Alguien mencionó que te escribiría.",
    "Software Development & Systems": "Desarrollo de Software y Sistemas",
    "Trusted by teams & founders": "Confían en nosotros equipos y fundadores",
    "The planner for designers and freelancers — order for your creative projects.": "El planner para diseñadores y freelancers — orden para tus proyectos creativos.",
    "Plan your week and your goals with calm and structure.": "Planifica tu semana y tus metas con calma y estructura.",
    "Plan your content, strategy and metrics in one calm Notion workspace.": "Planifica tu contenido, tu estrategia y tus métricas en un solo espacio Notion con calma.",
    "I'd be interested in working on other projects with you — for example, videos or posts with animations.": "Me interesaría hacer otros proyectos con usted — por ejemplo, videos o posts con animaciones.",
    "I wanted to thank you for the help with my personal branding — I got great reception on the posts...": "Quería agradecerte la ayuda con mi branding personal — tuvo muy buena acogida en las publicaciones...",
    "Read full review →": "Leer completo →",

    /* BLOG · artículo único (sinopsis + compra) */
    "Blog": "Blog",
    "The book ·": "El libro ·",
    "Synopsis": "Sinopsis",
    "I quit, I trembled…": "Renuncié, tembló…",
    "and Alquimia was born.": "y nació Alquimia.",
    "The story of El diario imperfecto de una creadora — what happens inside its pages, and why you'll want to read it to the last exercise.": "La historia de El diario imperfecto de una creadora — lo que pasa dentro de sus páginas y por qué vas a querer leerla hasta el último ejercicio.",
    "This is not an expert's book. It's my imperfect diary.": "Esto no es un libro de experta. Es mi diario imperfecto.",
    "One night I had had enough: $8 posts, gifted nights, and a heart that was done. So I quit — and then I trembled in front of the empty calendar.": "Una noche ya no di más: posts de $8, noches regaladas y un corazón que ya no daba. Renuncié — y después temblé frente al calendario vacío.",
    "From that rubble Alquimia was born: a one-woman studio built from an anime, a feeling and a lot of guerrilla resourcefulness.": "De esos escombros nació Alquimia: un estudio de una sola mujer construido con un anime, una sensación y muchos recursos de guerrilla.",
    "And then the real battle began: learning to work with AI instead of fighting it — from sworn enemy to trusted assistant, and why a pretty logo made by AI doesn't make a brand.": "Y entonces empezó la batalla real: aprender a trabajar con IA en vez de pelear con ella — de enemiga jurada a asistente de confianza, y por qué un lindo logo hecho por IA no hace una marca.",
    "Inside you'll find real chapters, unfinished endings, 15 prompts to copy and paste, exercises with space to write, and a launch checklist — the map I wish I'd had.": "Adentro vas a encontrar capítulos reales, finales abiertos, 15 prompts para copiar y pegar, ejercicios con espacio para escribir y un checklist de lanzamiento — el mapa que yo hubiera querido tener.",
    "No smoke here. Just the real thing.": "Aquí no hay humo. Hay lo real.",
    "The diary's guardian · original illustration": "La guardiana del diario · ilustración original",
    "What's inside the diary": "Lo que hay dentro del diario",
    "Where it all begins.": "Por dónde empieza todo.",
    "The night I decided: no more.": "La noche en que decidí: no más.",
    "How Alquimia was born.": "Cómo nació Alquimia.",
    "From sworn enemy to trusted assistant.": "De enemiga jurada a asistente de confianza.",
    "A pretty icon doesn't make a brand.": "Un ícono bonito no hace una marca.",
    "Organizing the chaos with guerrilla resources.": "Organizar el caos con recursos de guerrilla.",
    "The opening of a new world.": "La apertura de un nuevo mundo.",
    "Prompts, tools and launch checklist.": "Prompts, herramientas y checklist de lanzamiento.",
    "Get the book": "Consigue el libro",
    "Read synopsis": "Leer sinopsis",
    "Chapters, prompts, exercises with space to write, and a launch checklist — all in one imperfect diary.": "Capítulos, prompts, ejercicios con espacio para escribir y un checklist de lanzamiento — todo en un diario imperfecto.",
    "Buy the book 💜": "Comprar el libro 💜"
  };

  var placeholders = {
    "Reason, comments...": "Motivo, comentarios...",
    "Your name": "Tu nombre",
    "Your email": "Tu correo",
    "Subject": "Asunto",
    "Tell me about your project...": "Cuéntame sobre tu proyecto...",
    "your@email.com": "tu@email.com"
  };

  var titles = {
    "Delete my data · Kore · Alquimia Lab": "Eliminar mis datos · Kore · Alquimia Lab",
    "Alquimia Lab · Well-being, order & design": "Alquimia Lab · Bienestar, orden y diseño",
    "Portfolio · Alquimia Lab": "Portafolio · Alquimia Lab",
    "User Experience Design · Alquimia Lab": "Diseño de Experiencia de Usuario · Alquimia Lab",
    "Social Media Campaign · Alquimia Lab": "Campaña de Redes Sociales · Alquimia Lab",
    "AI Characters · Alquimia Lab": "Personajes IA · Alquimia Lab",
    "Brand Identity Exploration · Alquimia Lab": "Exploración de Identidad de Marca · Alquimia Lab",
    "Products · Alquimia Lab": "Productos · Alquimia Lab",
    "Contact · Alquimia Lab": "Contacto · Alquimia Lab",
    "Planner 2027 · Calma y Orden · Alquimia Lab": "Planificador 2027 · Calma y Orden · Alquimia Lab",
    "Privacy Policy · Alquimia Lab": "Política de Privacidad · Alquimia Lab",
    "Kore · Coming Soon · Alquimia Lab": "Kore · Próximamente · Alquimia Lab",
    "Kore - Coming Soon · Alquimia Lab": "Kore - Próximamente · Alquimia Lab",
    "Kore · Your calm space · Alquimia Lab": "Kore · Tu espacio de calma · Alquimia Lab",
    "Kore": "Kore",
    "Your calm space": "Tu espacio de calma",
    "Under development": "En desarrollo",
    "Coming soon to Google Play": "Próximamente en Google Play",
    "Kore is in final development phase. It will be your personal calm space: tasks, habits, notes, diary, relaxing music and chat with Antonio (AI).": "Kore está en fase final de desarrollo. Será tu espacio personal de calma: tareas, hábitos, notas, diario, música relajante y chat con Antonio (IA).",
    "Tasks & Habits": "Tareas & Hábitos",
    "Notes & Diary": "Notas & Diario",
    "Relaxing Music": "Música Relajante",
    "AI Chat (Antonio)": "Chat IA (Antonio)",
    "Do you want to delete your Kore data?": "¿Deseas eliminar tus datos de Kore?",
    "Delete my data": "Eliminar mis datos",
    "Want to be notified when it launches?": "¿Quieres que te avise cuando salga?",
    "Notify me when it launches": "Avísame cuando salga",
    "Notify me": "Avísame",
    "Made with calm & coffee by": "Hecho con calma y café por",
    "Privacy": "Privacidad",
    "Delete account": "Eliminar cuenta",
    "Terms": "Términos",
    "Blog · Alquimia Lab": "Blog · Alquimia Lab"
  };

  var descriptions = {
    "Alquimia Lab · Privacy Policy. Information about data collection, cookie use, user rights and more.": "Alquimia Lab · Política de Privacidad. Información sobre recopilación de datos, uso de cookies, derechos de los usuarios y más.",
    "Request deletion of your personal data in Kore.": "Solicita la eliminación de tus datos personales en Kore.",
    "Alquimia Lab — Products for your well-being and order + Professional design. Notion templates, coloring books, and design services.": "Alquimia Lab — Productos para tu bienestar y orden + Diseño profesional. Plantillas de Notion, libros para colorear y servicios de diseño.",
    "Alquimia Lab Portfolio — Visual designer, branding, UI/UX, illustration, and packaging.": "Portafolio Alquimia Lab — Diseñadora visual, branding, UI/UX, ilustración y empaques.",
    "Alquimia Lab Portfolio — User Experience Design.": "Portafolio Alquimia Lab — Diseño de Experiencia de Usuario.",
    "Alquimia Lab Portfolio — Social Media Campaigns.": "Portafolio Alquimia Lab — Campañas de Redes Sociales.",
    "Alquimia Lab Portfolio — AI Characters.": "Portafolio Alquimia Lab — Personajes IA.",
    "Alquimia Lab Portfolio — Brand Identity Exploration.": "Portafolio Alquimia Lab — Exploración de Identidad de Marca.",
    "Alquimia Lab Products — Notion templates, coloring books, and productivity tools.": "Productos Alquimia Lab — Plantillas de Notion, libros para colorear y herramientas de productividad.",
    "Alquimia Lab Contact — Let's talk about your next project.": "Contacto Alquimia Lab — Hablemos de tu próximo proyecto.",
    "Calma y Orden — Planner 2027. A minimalist hybrid journal for self-care and productivity. Print on Amazon, digital on Gumroad.": "Calma y Orden — Planificador 2027. Un journal híbrido minimalista de autocuidado y productividad. Impreso en Amazon, digital en Gumroad.",
    "Alquimia Lab — Privacy Policy · GDPR/LOPD Compliance": "Alquimia Lab — Política de Privacidad · Cumplimiento GDPR/LOPD",
    "Alquimia Lab — Privacy Policy for our website and services": "Alquimia Lab — Política de Privacidad para nuestro sitio web y servicios",
    "Kore · Coming Soon · Alquimia Lab": "Kore · Próximamente · Alquimia Lab",
    "Kore · Your calm space · Alquimia Lab": "Kore · Tu espacio de calma · Alquimia Lab",
    "Kore is your calm space: tasks, habits, notes, diary, lo‑fi music and an AI assistant — all in one app.": "Kore es tu espacio de calma: tareas, hábitos, notas, diario, música lo‑fi y un asistente con IA — todo en una sola app.",
    "Coming soon · by Alquimia Lab": "Muy pronto · por Alquimia Lab",
    "Your calm space: tasks, habits, notes, diary, lo‑fi music and an AI assistant — all in one app.": "Tu espacio de calma: tareas, hábitos, notas, diario, música lo‑fi y un asistente con IA — todo en una sola app.",
    "Android · Coming soon on Google Play": "Android · Próximamente en Google Play",
    "View Kore →": "Ver Kore →",
    "Kore App": "App Kore",
    "The story of El diario imperfecto de una creadora — what happens inside its pages, and why you'll want to read it to the last exercise.": "La historia de El diario imperfecto de una creadora — lo que pasa dentro de sus páginas y por qué vas a querer leerla hasta el último ejercicio.",
    "Alquimia Lab — Notion templates, planners, coloring books, Lofi mixes and Kore, your calm app. Design tools for a calmer day.": "Alquimia Lab — Plantillas de Notion, planners, libros para colorear, mixes Lofi y Kore, tu app de calma. Herramientas de diseño para un día con más calma."
  };

  var nodes = [], phNodes = [], titleSnap, descSnap;

  (function capture() {
    var w = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, {
      acceptNode: function (n) {
        var p = n.parentNode;
        if (p && p.tagName && /^(SCRIPT|STYLE|TEXTAREA|NOSCRIPT|SVG|SELECT|OPTION)$/.test(p.tagName)) {
          return NodeFilter.FILTER_REJECT;
        }
        return NodeFilter.FILTER_ACCEPT;
      }
    });
    var n;
    while ((n = w.nextNode())) {
      nodes.push({ n: n, t: n.nodeValue });
    }
    var ph = document.querySelectorAll("[placeholder]");
    for (var i = 0; i < ph.length; i++) {
      phNodes.push({ el: ph[i], v: ph[i].getAttribute("placeholder") });
    }
    titleSnap = document.title;
    var meta = document.querySelector('meta[name="description"]');
    descSnap = meta ? meta.getAttribute("content") : null;
  })();

  function restore() {
    for (var i = 0; i < nodes.length; i++) nodes[i].n.nodeValue = nodes[i].t;
    for (var j = 0; j < phNodes.length; j++) phNodes[j].el.setAttribute("placeholder", phNodes[j].v);
    if (titleSnap !== null) document.title = titleSnap;
    var meta = document.querySelector('meta[name="description"]');
    if (descSnap !== null && meta) meta.setAttribute("content", descSnap);
  }

  function applyLang(l) {
    restore();
    if (l === "es") {
      var key, node, lead, trail;
      for (var i = 0; i < nodes.length; i++) {
        node = nodes[i].n;
        if (!node.nodeValue) continue;
        key = node.nodeValue.replace(/\s+/g, " ").trim();
        if (dict.hasOwnProperty(key)) {
          lead = node.nodeValue.match(/^\s*/)[0];
          trail = node.nodeValue.match(/\s*$/)[0];
          node.nodeValue = lead + dict[key] + trail;
        }
      }
      for (var j = 0; j < phNodes.length; j++) {
        if (placeholders.hasOwnProperty(phNodes[j].v)) {
          phNodes[j].el.setAttribute("placeholder", placeholders[phNodes[j].v]);
        }
      }
      if (titles.hasOwnProperty(titleSnap)) document.title = titles[titleSnap];
      var meta = document.querySelector('meta[name="description"]');
      if (descSnap !== null && meta && descriptions.hasOwnProperty(descSnap)) {
        meta.setAttribute("content", descriptions[descSnap]);
      }
      document.documentElement.setAttribute("lang", "es");
    } else {
      document.documentElement.setAttribute("lang", "en");
    }
    var btn = document.getElementById("langToggle");
    if (btn) {
      btn.setAttribute("data-lang", l);
      btn.innerHTML = '<span class="cur" data-cur>ES</span><span class="sep">|</span><span class="cur" data-cur>EN</span>';
      var cur = btn.querySelectorAll("[data-cur]");
      cur[0].style.opacity = l === "es" ? "1" : ".45";
      cur[1].style.opacity = l === "en" ? "1" : ".45";
      btn.setAttribute("aria-label", l === "es" ? "Switch to English" : "Cambiar a Español");
    }
    try { localStorage.setItem(STORE_KEY, l); } catch (e) { /* ignore */ }
  }

  function detectLang() {
    try {
      var n = (navigator.language || navigator.userLanguage || "es").toLowerCase();
      // Preferimos inglés para hispanohablantes de EE.UU./posibles angloparlantes
      if (n.indexOf("en") === 0) return "en";
      return "es";
    } catch (e) { return "es"; }
  }

  var lang = null;
  try { lang = localStorage.getItem(STORE_KEY); } catch (e) { /* ignore */ }
  if (lang !== "es" && lang !== "en") lang = detectLang();
  applyLang(lang);

  document.addEventListener("click", function (e) {
    var t = e.target;
    if (!t) return;
    var btn = (t.tagName && t.tagName.toLowerCase() === "button" && t.id === "langToggle") ? t : (t.parentNode && t.parentNode.id === "langToggle" ? t.parentNode : null);
    if (btn) {
      var cur = document.documentElement.getAttribute("lang") === "es" ? "es" : "en";
      applyLang(cur === "es" ? "en" : "es");
    }
  });
})();